# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openapi_client.models.expires_after import ExpiresAfter
from typing import Optional, Set
from typing_extensions import Self

class CreateVectorStoreRequest(BaseModel):
    """
    Request model for creating a new vector store.
    """ # noqa: E501
    chunking_strategy: Optional[Dict[str, Any]] = Field(default=None, description="Defines the chunking strategy for vector stores.")
    expires_after: Optional[ExpiresAfter] = None
    file_ids: Optional[List[StrictStr]] = None
    metadata: Optional[Dict[str, StrictStr]] = None
    name: StrictStr
    __properties: ClassVar[List[str]] = ["chunking_strategy", "expires_after", "file_ids", "metadata", "name"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CreateVectorStoreRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of expires_after
        if self.expires_after:
            _dict['expires_after'] = self.expires_after.to_dict()
        # set to None if expires_after (nullable) is None
        # and model_fields_set contains the field
        if self.expires_after is None and "expires_after" in self.model_fields_set:
            _dict['expires_after'] = None

        # set to None if file_ids (nullable) is None
        # and model_fields_set contains the field
        if self.file_ids is None and "file_ids" in self.model_fields_set:
            _dict['file_ids'] = None

        # set to None if metadata (nullable) is None
        # and model_fields_set contains the field
        if self.metadata is None and "metadata" in self.model_fields_set:
            _dict['metadata'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CreateVectorStoreRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "chunking_strategy": obj.get("chunking_strategy"),
            "expires_after": ExpiresAfter.from_dict(obj["expires_after"]) if obj.get("expires_after") is not None else None,
            "file_ids": obj.get("file_ids"),
            "metadata": obj.get("metadata"),
            "name": obj.get("name")
        })
        return _obj


