ARG CUDA_IMAGE="12.2.2-devel-ubuntu22.04"
FROM --platform=amd64 nvidia/cuda:${CUDA_IMAGE}

## Top level args / env vars
ARG USER=user
ARG USER_UID=1000
ARG USER_GID=$USER_UID
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
ENV DEBIAN_FRONTEND=noninteractive
ENV NODE_VERSION=21.x

## Install python + opencl + blas
RUN apt-get update && apt-get upgrade -y \
    && apt-get install -y git build-essential \
    python3 python3-dev python3-pip python-is-python3 gcc wget \
    ocl-icd-opencl-dev opencl-headers clinfo \
    libclblast-dev libopenblas-dev libcairo2-dev \
    && mkdir -p /etc/OpenCL/vendors && echo "libnvidia-opencl.so.1" > /etc/OpenCL/vendors/nvidia.icd \
    && rm -rf /var/lib/apt/lists/*

## Apt based dependencies
RUN apt-get update -y \
    && apt-get upgrade -y \
    && apt-get -y install \
    curl \
    git \
    vim \
    wget \
    procps \
    inotify-tools \
    ca-certificates \
    && rm -rf /var/lib/apt/lists/*

## Create unpriv user
RUN groupadd --gid $USER_GID $USER \
    && useradd --uid $USER_UID --gid $USER_GID -m $USER \
    && apt-get update \
    && apt-get install -y sudo \
    && echo $USER ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/$USER \
    && chmod 0440 /etc/sudoers.d/$USER \
    && chmod -R 775 /usr/local

# Install node
RUN curl -sL https://deb.nodesource.com/setup_${NODE_VERSION} | bash - && \
    apt-get install -y nodejs --no-install-recommends && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Install node global deps
ARG OPENAPI_GENERATOR_VERSION=2.15.3
RUN npm install -g \
    @openapitools/openapi-generator-cli@${OPENAPI_GENERATOR_VERSION} \
    typescript \
    pnpm@latest-10

USER ${USER}
RUN python3 -m pip install --user uv

## Install oh my zsh
# Uses "Spaceship" theme with some customization. Uses some bundled plugins and installs some more from github
RUN sh -c "$(wget -O- https://github.com/deluan/zsh-in-docker/releases/download/v1.1.5/zsh-in-docker.sh)" -- \
    -t https://github.com/denysdovhan/spaceship-prompt \
    -a 'SPACESHIP_PROMPT_ADD_NEWLINE="false"' \
    -a 'SPACESHIP_PROMPT_SEPARATE_LINE="false"' \
    -p git \
    -p ssh-agent \
    -p https://github.com/zsh-users/zsh-autosuggestions \
    -p https://github.com/zsh-users/zsh-completions